name: 'Auto Assign Reviewr'
on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: (! github.event.pull_request.draft) && contains(toJson(github.event.pull_request.requested_reviewers), '[]' )
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'
          
      - run: |
          echo "ths is env=${{ github.event.pull_request.requested_reviewers }}"
