name: 'Auto Assign Reviewr'
on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: (! github.event.pull_request.draft) && contains(toJson(github.event.pull_request.requested_reviewers), "[]" )
    steps:
    
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@もう一回'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          
      - if: github.event.type != 'Created' || steps.check.outputs.triggered == 'true'
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'
