name: 'Auto Assign Reviewr'
on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, ready_for_review, reopened]
    
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: (! github.event.pull_request.draft) && contains(toJson(github.event.pull_request.requested_reviewers), '[]' )
    steps:
    
      - name: 自動割り当て
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'
          
      - name: 誰に割り当てられたか確認するために同じページを呼ぶ
        uses: indiesdev/curl@v1
        id: api
        with:
          url: ${{ github.event.pull_request._links.self.href }}
        
      - name: GITHAB_NAME_TO_DISCORD_IDをデコードして割り当てられた人をKEYとしてDiscordIDをファイルに保存
        env:
          JSON_DECODE: ${{ secrets.GITHAB_NAME_TO_DISCORD_ID }}
          KEY: ${{ fromJson(steps.api.outputs.response).data.requested_reviewers[0].login }}
        run: |
          echo $JSON_DECODE | base64 --decode | jq -r '."${{ env.KEY }}"' >> TEMP_DISCORD_ID.txt
          
      - name: DiscordIDをファイルから変数に
        id: setID
        run: |
          echo ::add-mask::$(cat TEMP_DISCORD_ID.txt)
          echo ::set-output name=DISCORD_ID::$(cat TEMP_DISCORD_ID.txt)
          
      - name: Discordに通知
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '<@${{ steps.setID.outputs.DISCORD_ID }}> レビュ－お願いします。\n${{ github.event.pull_request._links.self.href }}'
                
