name: 'Auto Assign Reviewr'
on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, ready_for_review, reopened]
    
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: (! github.event.pull_request.draft) && contains(toJson(github.event.pull_request.requested_reviewers), '[]' )
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'
          
      - name: 'Call API'
        uses: indiesdev/curl@v1
        id: api
        with:
          url: ${{ github.event.pull_request._links.self.href }}
        
      - name: Translate secrets of base64 into json
        env:
          JSON_DECODE: ${{ secrets.GITHAB_NAME_TO_DISCORD_ID }}
          KEY: Shi-553 #${{ fromJson(steps.api.outputs.response).data.requested_reviewers[0].login }}
        run: |
          echo $JSON_DECODE | base64 --decode | jq .$KEY -r
                
                
      
        
