name: 'Auto Assign Reviewr'
on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.requested_reviewers), "[]" )
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'
